// 05-DEVELOPMENT.md §10.7 — escopos de §10.3.
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'refactor',
        'test',
        'chore',
        'perf',
        'style',
        'build',
        'ci',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'autenticacao',
        'perfil',
        'contas',
        'categorias',
        'etiquetas',
        'movimentacoes',
        'transferencias',
        'anexos',
        'cartoes',
        'faturas',
        'compartilhadas',
        'convites',
        'metas',
        'orcamentos',
        'notificacoes',
        'dashboard',
        'relatorios',
        'pesquisa',
        'auditoria',
        'banco',
        'api',
        'ui',
        'infra',
        'docs',
        'deps',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
    'body-max-line-length': [2, 'always', 100],
  },
};
