import {
  Baby,
  Banknote,
  Book,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Cat,
  Clock,
  Coins,
  CreditCard,
  Dog,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Leaf,
  Minus,
  Moon,
  Music,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Stethoscope,
  Sun,
  Tag,
  Train,
  TrendingDown,
  TrendingUp,
  Truck,
  Tv,
  Umbrella,
  Undo2,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Conjunto curado (nao a biblioteca Lucide inteira) que serve tanto de
// registro de renderizacao (nome -> componente) quanto de opcoes do
// seletor com busca (issue #29). Cobre os icones padrao das 18 categorias
// do sistema e das contas, mais variedade suficiente para a busca fazer
// sentido.
export const ICONES: Record<string, LucideIcon> = {
  wallet: Wallet,
  landmark: Landmark,
  banknote: Banknote,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  coins: Coins,
  'building-2': Building2,
  smartphone: Smartphone,
  briefcase: Briefcase,
  laptop: Laptop,
  undo: Undo2,
  'plus-circle': Plus,
  'minus-circle': Minus,
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  car: Car,
  home: Home,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  'party-popper': PartyPopper,
  repeat: Repeat,
  shirt: Shirt,
  dog: Dog,
  cat: Cat,
  baby: Baby,
  gift: Gift,
  tag: Tag,
  plane: Plane,
  bus: Bus,
  train: Train,
  truck: Truck,
  fuel: Fuel,
  wifi: Wifi,
  phone: Phone,
  tv: Tv,
  'gamepad-2': Gamepad2,
  book: Book,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  scissors: Scissors,
  wrench: Wrench,
  hammer: Hammer,
  music: Music,
  film: Film,
  camera: Camera,
  umbrella: Umbrella,
  sun: Sun,
  moon: Moon,
  clock: Clock,
  flame: Flame,
  leaf: Leaf,
};

export const ICONE_PADRAO: LucideIcon = Tag;

export function resolverIcone(nome: string): LucideIcon {
  return ICONES[nome] ?? ICONE_PADRAO;
}
